### ISSUE TITLE
Cannot build docker images

### ISSUE THREAD

**Issue by TyphooN-** [itsmesivaa/stock_catalyst#1]
docker build -f Dockerfile_webscrape -t itsmesivaa/webscrape:latest .

Step 18/21 : COPY NSEBhavcopy.sqlite .
COPY failed: file not found in build context or excluded by .dockerignore: stat NSEBhavcopy.sqlite: file does not exist

docker build -f Dockerfile_stockcatalyst -t itsmesivaa/stockcatalyst:latest .
Step 12/14 : COPY NSEBhavcopy.sqlite .
COPY failed: file not found in build context or excluded by .dockerignore: stat NSEBhavcopy.sqlite: file does not exist

**Comment by itsmesivaa** [comment]
Thanks for writing **Mr. TyphooN** i'd suggest you clone my project and try to build a docker file with your your own local DB in this case... Because of the size constraint i've not uploaded the NSEBhavcopy.sqlite database. I tried to manage that independently on SQLiteCloud it didn't went well as expected but may be in future i can scale that. 

If you got any idea please let me know... Have a nice day!

Regards,
Siva
